### ISSUE TITLE
Mac OS connection problem

### ISSUE THREAD

**Issue by Niminem** [dom96/webdriver#11]
I've downloaded the same webdriver version specified in your gecko-travis example, extracted the driver and moved it into my path (usr/local/bin), created a simple script similar to the one here, and I keep getting "connection refused" when trying to create a session. I've even switched Nim from 1.4.0 to 1.2.2 to test.

I'm using Mac 10.15.5 if this may mean anything.

Any idea what could possibly be the issue here?

**Comment by dom96** [comment]
it's running on a different port?

**Comment by Niminem** [comment]
You're right :(

I didn't pay attention to the `when is main module` call within the travis example, that shows how you actually open the driver with the `-p #portnumber` flag and within a new thread. Maybe this can help others if this is also specified in the readme?

**Comment by dom96** [comment]
sure, make a PR :)
